services:
  demo:
    build: .
    restart: unless-stopped
    ports:
      - "5006:5006"
    volumes:
      - model-data:/home/mambauser/.cache
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  model-data:
