name: Build and push image to Google Artifact Registry

on:
  push:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host

      - name: Compute image tag
        id: compute-image-tag
        run: |
          short_sha=$(git rev-parse --short ${{ github.sha }})
          echo "tag=${{ github.triggering_actor }}/audiovlm-demo:$short_sha" >> $GITHUB_OUTPUT
          echo "short_sha=$short_sha" >> $GITHUB_OUTPUT          

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: dockerfile
          tags: localhost:5000/${{ steps.compute-image-tag.outputs.tag }}
